### ISSUE TITLE
This is depressing...

### ISSUE THREAD

**Issue by oising** [RealEstateCore/rec#106]
Why not get together with the guys over at https://brickschema.org/ and collaborate instead of further fragmenting the market?

**Comment by erikoskarwallin** [comment]
Oisian,
I do agree with you that we need more cooperation and alignment. The approach of the RealEstateCore Consortium is to reach out and work together to make alignments (e.g. https://github.com/BrickSchema/Brick/tree/master/alignments/rec, see here for more: https://github.com/RealEstateCore/rec/tree/master/ontology/alignments). Hopefully we can narrow down the number of "languages" that exists.
The purpose of RealEstateCore is to model the property owner/operator's perspective (and re-use the explicit details of e.g. Brick if you need to make something more complex like  a SCADA-system based on semantics). RealEstateCore has/in-the-making extensive support for the business-side of smart buildings connected to smart city, grids, etc.
We in RealEstateCore welcome initiatives to work closer to align and re-use. James Dice (https://www.linkedin.com/in/jwdice/) has started to bring us ontology-makers together.

**Comment by hammar** [comment]
Thanks @oising and @erikoskarwallin for your comments on this. It is of course important that the community does not diverge/fracture too much. I hope the aforementioned initiatives and others (see also https://github.com/Azure/opendigitaltwins-building) can bridge the gaps. In the meanwhile, I'll be closing this issue; but if you want to continue the debate/discussion, feel free to reopen it.
