### ISSUE TITLE
Is Premises deprecated?

### ISSUE THREAD

**Issue by jbkoh** [RealEstateCore/rec#112]
Hi there, I was looking at the website (https://doc.realestatecore.io/3.2/lease.html) and the WebVOWL shows that `Premises` has been deprecated. I checked the master branch (https://github.com/RealEstateCore/rec/blob/master/ontology/core.rdf#L1139) and I don't see any deprecated flag.

Is it a bug in the visualization or is it really deprecated?

Thanks!

**Comment by hammar** [comment]
Hi,

Apologies for the delay in responding! 

The Premises class in the Lease module is in fact deprecated in the currently released version of the ontology and its master branch (see https://github.com/RealEstateCore/rec/blob/0eb2db6f8dd91bcf6709c4fa3f5589fb32f70bcc/ontology/lease.rdf#L307). That deprecated version of the class has a different IRI (https://w3id.org/rec/lease/Premises) than the one in the core module that you are referring to, which is not (yet, see below) deprecated.

In the development branch (https://github.com/RealEstateCore/rec/tree/develop/ontology) the latter is also deprecated, in favour of the more generic abstraction SpaceCollection and its subclasses:

* core:SpaceCollection
    - core:Apartment
    - core:Campus
    - core:RealEstate
    - business:TenantUnit

I'd recommend using the latter if you are building for the future; that development branch will be released shortly.

Closing the issue under the assumption this answers the question -- but if it does not, feel free to re-open and continue the questions/discussion!

Best,

Karl
