### ISSUE TITLE
Implement Presence modelling

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#12]
Bring presence semantics natively into REC. E.g., "How many people are in the conference room", "What is the typical utilization of the conference room", "Which paths do people typically take from room X to room Y", etc.

**Comment by hammar** [comment]
Technical commitee decision 2020-05-25: @perkarlberg will implement based on ProptechOS design before end of June.

**Comment by erikoskarwallin** [comment]
Need to add QuantityKind:
AreaPresence - Number of people counted in a specified area (at the observation time)
Footfall - Number of people crossing a specified line (at the observation time)
PlacementContext
DirectionInward - The inward direction of an observation for e.g. Presence (Footfall) - to be able to differentiate between directions
DirectionOutward - The outward direction of an observation for e.g. Presence (Footfall) - to be able to differentiate between directions
