### ISSUE TITLE
Specify a measurement unit for altitude in isLocatedAt 

### ISSUE THREAD

**Issue by sweco-secfbr** [RealEstateCore/rec#126]
isLocatedAt: An object that has an exact point (expressed in WGS84 in decimal degrees as (latitude,longitude,altitude).
Please add declaration of altitude. I suggest metre above sea level. https://sv.wikipedia.org/wiki/Altitud

**Comment by hammar** [comment]
Hi,

I think this is covered by either `asWkt`, `asGML`, or `isLocatedAtLocalCoordinates` in the 3.3 development branch. The intended design pattern is as follows:

```
Entity -- hasGeometry --> Geometry
Geometry -- hasSerialization --> (WKT, GML, local coordinates, etc)
```

This mirrors the established GeoSPARQL design but extends it using OWL sub-properties, i.e., there is a generic superproperty `hasSerialization` and a number of datatype specific subproperties to that which provide a variety of serialization options, from coordinate syntaxes to spatial labels, including:

* `asGML`
* `asWKT`
* `hasCity`
* `hasCountry`
* `isLocatedAtLocalCoordinates`
* ... etc

Admittedly, while quite generic, this design is a little inaccessible to our target users, particularly as pertains to places, and we may need to simplify it. For adressing (street adresses and so forth) I have a PR here: https://github.com/RealEstateCore/rec/pull/123

For coordinates/geometries, I wonder if the above generic design pattern could still work though -- what do you think? If it is inappropriate, do you have any suggestions for specs to look into? We would want to avoid reinventing the wheel here, it would be more beneficial to latch onto an existing and usable spec if possible.

**Comment by hammar** [comment]
Apologies @sweco-secfbr, I actually managed to misread your question and answer something else entirely. One shouldn't be triaging issues late in the evening. My bad!

Followup on the measurement unit definition:

* `isLocatedAtLocalCoordinates` from the development branch specifies meters in relation to the local origo. The name of this property isn't great, but it works.
* `asGML` allows, if I understand GML properly (which cannot be guaranteed) alignment against coordinate reference systems that should allow some sort of global positioning which would I assume include units

**Comment by hammar** [comment]
REC4 uses GeoJSON, which in the default case, unless another reference system is specified, decimal degree for lat/long and meters for altitude (see https://geojson.org/geojson-spec.html#coordinate-reference-system-objects). In light of that, this issue can be closed. Let me know if I've misunderstood and we need to open it again.
