### ISSUE TITLE
isLocatedAtLocalCoordinates missing definition of what's considered to be up direction

### ISSUE THREAD

**Issue by sweco-secfbr** [RealEstateCore/rec#127]
isLocatedAtLocalCoordinates: Literal value in meter (x,y,z) in a local coordinate system that referes to GeoReferenceOrigo.
In relation to a building I suggest that positive z-direction points vertical towards the roof and the xy-plane is horizontal.
Does this make sense?

**Comment by hammar** [comment]
That makes sense, and is how I would interpret the definition already, even though it is not made explicit. Current (3.3 development branch) definition is as follows:

> Expressed as a string adhering to the notation "(x,y,z)", where x, y, and z ar whole or decimal numbers indicating the position in the local building coordinate system, measured in meters. This relates to the outside world coordinate refence system via the values expressed by GeoReferenceOrigo.

Would inserting something like the following sentence after the first be sufficient?

> The x and y coordinates indicate the horizontal plane (in turn aligned against the north-south meridian using the property hasGeoReferenceBearing) whereas the z coordinate indicates vertical (up-down) direction.

**Comment by hammar** [comment]
In REC4 the isLocatedAtLocalCoordinates is replaced by a property `geometry` that can be assigned to Assets and Spaces, the value of which is a GeoJSON polygon. The GeoJSON spec does seem to cover this definition well enough that we can close this issue now. Feel free to reopen if I've misunderstood and the issue remains.
