### ISSUE TITLE
Missing Equipment HVAC Sensor

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#138]
When an HVAC hot water system (sv "värmekrets") is modelled with a HVACHotWaterSystem collection the assets/equipments that comprises the system may be included. However, for this particular case the equipments typically are pump, valve and a number of temp sensors directly in the pipes. The latter are missing from the asset HVACEquipment class.

Hence suggestion to add asset HVACSensor as subclass to HVACEquipment. This allows that the physical sensor may be associated with the room (space) it actually sits in.

This new asset may then have the TemperatureSensor capability.

**Comment by hammar** [comment]
There is a set of physical sensors (i.e., not capabilities) under Equipment -> ICTEquipment -> SensorEquipment. 

This mirrors the assumption that sensors are somehow connected / "IT things". That assumption may be faulty, in which case those sensors should perhaps be moved up out of that hierarchy (placed directly under Equipment?). 

Alternatively one might break this apart and place these sensors closer in the hierarchy to all the equipment they are typically deployed with, as I understand your suggestion to be.

This is largely a usability matter -- what do our users/experts expect? Should all sensors be clustered in one joint place, or should they be spread out across domains of the building? I would tend toward the former myself, but this is a discussion worth having.

Note that in future REC 4 we are working with the Brick consortium to adopt as much of their models for equipment/points as possible, so by the time we release REC 4 this issue may be "out of our hands".

**Comment by PeteHart** [comment]
I think it makes sense to have the sensor equipment clustered but then i feel it should - as you elude to @hammar - exist higher in the class hierarchy, under Equipment.

For me, the current ITC subclassing implies that this is retrofitted (IoT) sensors for the building. Whereas the HVAC sensors are build in from the beginning and typically specialized for the purpose of sitting in an air duct or a water pipe.

One can of course already now model an HVAC system with the SensorEquipment super class despite it being a subclass to ICT equipment. So this is just a matter of getting the abstraction correct.

**Comment by hammar** [comment]
I would be OK with a pull request moving these sensors up a step in the hierarchy. Might be good to double-check with the MS colleagues so everyone is on board there as well. But we also need to think in terms of timeline when we move towards REC 4 -- should we implement something like this (a new feature) in 3.X, or should 3.X only include bugfixes, etc. Something for the TC this next Monday?

**Comment by PeteHart** [comment]
With the introduction of BRICK in REC 4 this is the wrong forum for the issue and it should be closed here.

It is however unclear how a hot heating water loop is modelled with BRICK. The temperature sensors sits directly in the pipes which really aren't equipments. So I believe the original issue remains. How to handle?

**Comment by hammar** [comment]
Agreed, closing.

See Brick modelling recommendations at https://docs.brickschema.org/modeling/collections.html. These do not represent the actual pipes, only the equipments that are connected via some (non-represented) pipes. See also discussion at https://github.com/BrickSchema/Brick/issues/184#issuecomment-704519830. I'd suggest we figure out what the concrete use cases and needs are for pipes (I assume there may be more than just spatial location of sensors), and propose some ideas to the Brick community.
