### ISSUE TITLE
Extend REC with electrical equipment 

### ISSUE THREAD

**Issue by mwdhont-auge** [RealEstateCore/rec#139]
Hi,

We are running into some limitations with respect to the capabilities to model equipment in the renewable energy domain (Solar, EV, Battery ...). We made our own extensions, but we would love to contribute back to REC.

So, we are open to discuss how we can organize this. 

Michiel

**Comment by PeteHart** [comment]
Great @mwdhont-auge ... note that with REC 4 the equipment classes are taken from BRICK (link to nightly version of their ontology https://brickschema.org/ontology/Nightly/classes) I don't see a specific renewable energy equipment section but found for instance batteries in their ontology. Anyways, think your contribution would have to be to the BRICK team, but asking @hammar to chime in on recommended ways of working here...

**Comment by hammar** [comment]
Agree on that -- equipment and points are now imported from Brick, so it would make for the cleanest design to get those things into Brick rather than REC. @mwdhont-auge, do you have connections in the Brick community or should I initiate some contacts?

**Comment by mwdhont-auge** [comment]
Hi, sorry for my very late reply, I opened a topic here: https://groups.google.com/g/brickschema/c/97JERcCUikc
If you agree this is the right place to raise the question, this issue can be closed.

Thanks,
Michiel

**Comment by hammar** [comment]
Sounds like a good start. I'd be happy to listen in and maybe even participate on that discussion if it takes off (with the caveat that my domain knowledge is limited). Closing this for now, but if it bounces back, feel free to re-open.
