### ISSUE TITLE
Description of Brick-models

### ISSUE THREAD

**Issue by mwdhont-auge** [RealEstateCore/rec#160]
Hi,

Is it possible that the descriptions of Brick-models ('Definitions' in Brick terminology) are not listed here?

Michiel

**Comment by hammar** [comment]
Good catch, thanks! We translate rdfs:comment values into DTDL description fields, but Brick typically uses skos:definition for its NodeShape documentation. I'll add a couple of lines of code to our SHACL2DTDL translator to also ingest those SKOS definitions. This should hopefully show up in models by next week.

**Comment by mwdhont-auge** [comment]
Great, thanks!

**Comment by hammar** [comment]
Closed by PR #175
