### ISSUE TITLE
DTDL-version of Brick using '_', while REC is not

### ISSUE THREAD

**Issue by mwdhont-auge** [RealEstateCore/rec#161]
Why there is a different convention in naming files and classes between both ontologies?

**Comment by hammar** [comment]
For historical reasons, Brick uses Underscore_Case and REC uses PascalCase for model naming. When ingesting Brick, for provenance and ease-of-use with existing Brick workflows we retain their identifiers (though re-minted as DTMIs), and name the files accordingly. This has no effect on the utility of the models, and is merely stylistic. We cannot (and do not want to) force Brick to adopt the REC style; and for REC users accustomed to our models, we do not want a complete break with what they are used to.

**Comment by hammar** [comment]
Closing this as answered, but feel free to re-open if you would like to continue the discussion.
