### ISSUE TITLE
How come 'PV Generation System' is not present here?

### ISSUE THREAD

**Issue by mwdhont-auge** [RealEstateCore/rec#162]
https://brickschema.org/ontology/1.2/classes/PV_Generation_System

Seems to be in Brick since February 2021, so I'm wondering what's the reason this class is not present here.

Michiel

**Comment by hammar** [comment]
This looks to be an issue in upstream Brick; PV_Generation_System is there defined as an OWL class, but not as a SHACL NodeShape. @gtfierro, is this something that you'd like a bug report for?

**Comment by gtfierro** [comment]
Very strange that disappeared in Brick; please do file an issue for that -- thanks!

**Comment by hammar** [comment]
Submitted here: https://github.com/BrickSchema/Brick/issues/446

Thanks @mwdhont-auge for noticing! 

I'm closing this issue and we'll have it trickle down from Brick once we ingest 1.3.1 (?)
