### ISSUE TITLE
Great ontology! Looking for json(LD) examples/implementations.

### ISSUE THREAD

**Issue by baardl** [RealEstateCore/rec#17]
Hi.

Is there any posibillity to get list of json examples? 
I have looked at both code and doc, and found almost none.

Thanks.
Best regards
Bård Lind

**Comment by hammar** [comment]
Hi Bård,

First of all, apologies for the delay in communication -- we're just getting started with moving the REC community into GitHub proper, and I don't think anyone has been allocated the responsibility of responding to new issues. Which means it lands on me, and I've been on vacation :-)

We don't have a set of data examples yet. That would perhaps be rather useful. In the meantime, such example RDF data can be generated by hand, e.g., by using Protégé and creating instances directly. 

You can also check the Idun (one of the REC implementations) graph API at https://doc.realestatecore.io/api/2.3/. However, note that that is based on an earlier and rather incomplete version of the ontology. See also https://github.com/Vasakronan/Idun-Examples/tree/master/Idun-Streaming-Api/Consumer/netcore/Idun.StreamingApi.Examples/Idun.StreamingApi.Examples for streaming data examples, again using the older 2.3 version ontology. Note that none of these examples use RDF/JSON-LD; instead, the developers have manually grafted message syntaxes and APIs based on REC concepts. A highly prioritised development during the autumn is to construct a standard (auto-generated from the ontology) REC API. I will work on this for a couple of months at least, and will work toward "pure" RDF/JSON-LD syntax (if possible).

If you want to check out the REC community a bit more there is also a Slack channel (https://realestatecore.slack.com) that I could invite you to. Let me know your address and I'll send an email invite. 

I hope this provided some answers at least. Drop me a note if you'd like to discuss more.

**Comment by baardl** [comment]
Thank you for your extensive reply,Karl.
I would be happy to chat on Slack.
My mail is bard.lind@gmail.com

Bård

søn. 25. aug. 2019, 21:45 skrev Karl Hammar <notifications@github.com>:
