### ISSUE TITLE
Implement module "Swedish address norms" or similar

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#18]
We want to leave REC core as culture-agnostic as possible, but several partners have need of an (optional) module covering some Sweden-specific semantics. Those semantics include Lantmäteriets different data fields, e.g., fastighetsbeteckning (estate identifier), lägenhetsnummer (apartment number), Swedish street addresses and zip codes, etc. 

Peter Hartlev will suggest some needed fields/values from Willhem's perspective and either develop a module, or deliver materials to Karl for implementation.

This module is not tied to or blocking a particular REC release on the roadmap, but we are looking at probably including it in the 3.1 or 3.2 release.

**Comment by alisspers** [comment]
Regarding these suggested fields/values: Is there a draft somewhere that we can take part of?

Specifically what I'm after is any indication on how the street address will be modeled.

I've seen examples of both having three different columns for `street`, `street number` and `littera` (e.g. "Villavägen", "7", "B") as well as a single column for the whole `street address` (e.g. "Villavägen 7B").

I'd say that the latter would work better from an international perspective. This is also how for example Google seems to model it according to their [AddressValidationMetadata specification](address_line) (they call the field `address_line`)

Which alternative would you say is preferable?

**Comment by hammar** [comment]
Hi,

For the core REC modules we will probably want to be as culture-agnostic as possible. I'm thinking as relaxed a structure as possible, but with a possibility of specializing classes and/or properties for local cultures/standards.

For the Swedish module I think the colleagues from Willhem are looking at basing it on Lantmäteriet's standards. I don't know those standards myself, so don't know which way they will proceed. I would suggest you check with Peter Hartlev on the Slack channel.

**Comment by alisspers** [comment]
Peter pointed me to the current solution in 3.0 which includes the `hasPostalAddress` property which I interpret should include the full address (e.g. "Villavägen 7B"). At our end I actually don't see a reason to do it any other way, so I think we'll go with joining the properties into one.

Thanks for the reply/clarification!

**Comment by hammar** [comment]
This is being worked on for v 3.2 by Peter Hartlev

**Comment by hammar** [comment]
TODO: merge 3.1.1/3.2 dev branch back into Lantmäteriet branch, verify structure makes sense, merge back.
@hammar

**Comment by hammar** [comment]
Closed by merging Lantmäteriet branch
