### ISSUE TITLE
QUDT-units in DTDL

### ISSUE THREAD

**Issue by mwdhont-auge** [RealEstateCore/rec#201]
What's the best practice to include 'units' in a DTDL-graph?
Brick Schema has the relationship '[hasUnit](https://brickschema.org/ontology/1.3/relationships/hasUnit/)', towards a QUDT-unit, but the QUDT-units do not seem to be represented in DTDL.

Are there any plans to make this available soon?

**Comment by hammar** [comment]
There is some support for semantic units in DTDLv2, see the spec section at https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#semantic-types

We're using this to graft on semantic types on some Brick Points lastKnownValue field in a forthcoming PR, see #204 that we hope to merge soon. 

I hope this is useful. If you have additional questions, feel free to reopen the issue and continue discussions.

Best,

Karl
