### ISSUE TITLE
Add data interface

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#21]
Similar to the actuation interface that describes how to interact with an actuator there’s a need to be able to describe how to interact with a data platform. Basically defining the schema to be used in requests for a data series, the response format of data, and the URLs to request at. Such data interface may be used in connection with both “raw” as well as “constructed” data re workshop October 18 2019. And would typically be associated with a sensor or potentially a new Data class.

**Comment by hammar** [comment]
Is this covered by the design of the forthcoming Analytics module as discussed November 28?

**Comment by PeteHart** [comment]
Yeah most likely, but let me take a look at the actuation interface, key value modeling, before we close it please

**Comment by hammar** [comment]
Solved (I think?) as part of release 3.2 and #49. Feel free to reopen if I'm misinterpreting.
