### ISSUE TITLE
Add support for Time Interval

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#22]
We need support for time intervals. Typically for aggregates (example total energy over January 2019, average daily temperature in building XYZ October 1-14 2019,...). The OWL Time ontology owl-time has this support and can likely be used directly or as inspiration.

**Comment by hammar** [comment]
I second reusing W3C Time. If you can specify which exact parts of it that would be needed in a first version, I can clone those parts into REC. I'm thinking that the W3C Time ontology namespace is so established that we can reuse it but for long-term maintainability graft it onto REC by redefining it locally, as we did with the GeoSPARQL ontology.

**Comment by PeteHart** [comment]
Good, ill come back with concrete suggestion

**Comment by hammar** [comment]
Blocker for #19; moving to 3.2 milestone.

**Comment by hammar** [comment]
Decision at technical commitee 2020-05-25: implement a new data property hasIso8601Interval, with domain Event, range xsd:string (where documentation indicates that we require ISO8601 compliance). Implement new subproperty of this, "hasObservationInterval", with domain Observation. Ensure compliance w/ Analytics module. Responsible: @hammar
