### ISSUE TITLE
Inconsistency in sensors

### ISSUE THREAD

**Issue by Fuchio** [RealEstateCore/rec#224]
Hey REC devs,

I think I have found some inconsistencies between (at least) the humidity and temperature sensors. The temperature sensor contains a temperature observation component with a lastKnownValue property, while the humidity sensor has a property directly called lastKnownValue (no component). This means setting the values is different in these cases. 

Is this expected behaviour?

**Comment by hammar** [comment]
Hi,

Good catch! 

I think the background was an inconsistency b/w DTDL semantic types (that deal only w/ absolute humidity) and our upstream Brick sensors (that deal w/ relative humidity), and when that couldn't be resolved, this fell through. But even if we can't apply semantic types, we should still be able to apply an observation component schema. 

I will look into and try to resolve in a day or two.

Best,

Karl

**Comment by hammar** [comment]
I've addressed this inconsistency in PR #225, and initiated an issue in upstream Brick at https://github.com/BrickSchema/Brick/issues/461. Hopefully Brick will end up with the same solution as I've done here in #225, so we don't get diverging models. 

However, we still only use components for those lastKnownValues that have corresponding semantic types -- all the others ("Adjust_Sensor", etc) still use objects, for legacy/simplicity reasons. @Fuchio, do you think that too jarring of a difference? We could go to components for all sensor types I guess, though we might not have corresponding observation schemas for all of them -- e.g., a generic "NumericValueObservation" could be used as catch-all.

**Comment by Fuchio** [comment]
That is clear! Thank you for the quick response and implementation, really appreciated (again). Personally I think would be best to use a generic NumericValueObservation component for all values that do not have semantic types like humidity. This would also make changes easier in the future as they all 'import' the same DTDL model.

**Comment by hammar** [comment]
I updated that PR to cover the Point subclasses that are most easily matched to "event" type observations (i.e., Sensor, Alert, and Command). We may need to think a little more on the remaining types (Status, Parameter, Setpoint), but my guess is that that won't be until post 4.0 GA.
