### ISSUE TITLE
Add support for serial numbers (incl. MAC)

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#23]
There's a need to be able to annotate devices with serial numbers to keep tally on the installed base. This may potentially be MAC addresses where such exist/are used as serial numbers or are part thereof => a MAC address property should probably be a sub property to S/N.

**Comment by hammar** [comment]
1. Check existing aliasId stufff
2. If insufficient, establish data property w/ domain: Device, range: String

**Comment by PeteHart** [comment]
Have been going over this. I feel that hasAliasId implies that a certain individual has a record with a unique identifier (alias identity) in another data system. However, we're looking to keep the REC individuals database as the master for the gadgets and gizmos, or at least some of them, in which case there's not really another data system to refer to. Hence I think we can add hasSerialNumber data property to hasAuxiliaryData (and in cases where an external system is in place nothing hinders use of hasAliasId instead).

**Comment by PeteHart** [comment]
For both the proposed data properties we can consider to restrict domain to device, range will be a string (or if existing in xsd a MAC address for the latter). For the device this however requires that for instance appliances are considered devices in the future.

**Comment by hammar** [comment]
Decision at tech committee meeting 2020-05-25: Go ahead w/ hasSerialNumber and hasMACAddress data properties w/ domain Device, range (appropriate version/subclass of) xsd:string. This goes in the Device module. Assigned to @PeteHart
