### ISSUE TITLE
Include some additional room types from Brick

### ISSUE THREAD

**Issue by epaulson** [RealEstateCore/rec#242]
A bit back Sarah Macdougall went through and looked at some of the Brick rooms that they're using that aren't in REC - see this post: https://groups.google.com/g/brickschema/c/CvvoI4n9uSk 

There are others missing but these are some that we'd love to see - can we hash out some ideas of either adding these or suggested alternatives?

Brick   type | Real Estate Core equivalent
-- | --
Break_Room,   Breakroom | None
Cafeteria | CafeteriaRoom
Conference_Room | ConferenceRoom
Control_Room | UtilitiesRoom
Copy_Room | CopyingRoom
Cubicle | None
Electrical_Room | None
Entrance | Entrance
Equipment_Room | None
Hallway | Hallway
Janitor_Room | None
Laboratory | Laboratory
Lobby | None
Lounge | None
Mail_Room | MailRoom
Mechanical_Room | None
Office | Office
Office_Kitchen | Kitchenette
Open_Office | None
Reception | Reception
Rest_Room | Bathroom
Room | Room
Security_Service_Room | SecurityRoom
Server_Room | DataServerRoom
Service_Room | UtilitiesRoom
Shower | ShowerRoom
Space | Space
Storage_Room | Storage
Team_Room | None

**Comment by Booli** [comment]
We would also love to be more precies regarding models of rooms in our DigitalTwin.
@hammar  How can we discuss this further?

**Comment by hammar** [comment]
Hi,

Great list, thanks! We certainly want to align with what exists in Brick already, to ensure a minimum of breakage. I've pulled out the unmatched room types from the table above and have commented on them individually below. Some are obvious additions to REC, for others I think a bit more clarity would be helpful, to ensure that we do not duplicate room types that we might already have -- and that we place new rooms in their proper place in the room taxonomy. 

Note that the REC Technical Committee is on a summer break and that the next scheduled call (at which PRs are cleared for merger) will be on September 7. Nonetheless, am pinging TC memberships to add visibility and possibly additional comments: @PeteHart @cbupp @erikoskarwallin 

Best,

Karl



Brick   type | Real Estate Core equivalent | Karl's comment
-- | -- | --
Break_Room,   Breakroom | None | Sure, should be added!
Cubicle | None | Not sure this should be modelled as a Room, which we generally take to be an enclosed area (to some degree). Propose the use of [Workspace](https://dev.realestatecore.io/ontology/Space/Architecture/Zone/Workspace) (subclass of Zone) instead.
Electrical_Room | None | I think this might be covered by (ElectricityRoom)[https://dev.realestatecore.io/ontology/Space/Architecture/Room/Utilities-/ElectricityRoom]?
Equipment_Room | None | Could we define more clearly what this is? Is it a room in which equipment is stored, or a room in which operating equipment that serves the building is mounted? Or something else?
Janitor_Room | None | Could we define more clearly what this is? Is it a staff room for janitors, a storage area for janitorial equipment, something else?
Lobby | None | What differentiates a Lobby from a Reception?
Lounge | None | Sure, should be added!
Mechanical_Room | None | Can we define a bit more closely?
Open_Office | None | Is this synonymous with (OfficeLandscape)[https://dev.realestatecore.io/ontology/Space/Architecture/Room/Office/-Landscape]?
Team_Room | None | Is a Team room distinct from a [ConferenceRoom](https://dev.realestatecore.io/ontology/Space/Architecture/Room/Conference-)

**Comment by epaulson** [comment]
On cubicle, I think we could live with it being a zone and not a room - the most important thing really is that it's some kind of a space and we can talk about its adjacency/connectivity and containment, so I wouldn't want to just call it a piece of furniture.

I'd be careful about making too many assumptions about enclosed-ness for rooms - I think the fire folks are going to have the most stringent requirements on what is a room and what isn't. I'm hoping we can get some of those folks involved here soon - let's talk about it the next time we chat.

**Comment by epaulson** [comment]
Equipment_room is an oddball in Brick - we have it subclassed from TelecommRoom, to set it apart from distribution rooms like IDFs/MDFs (e.g. https://en.wikipedia.org/wiki/Intermediate_distribution_frame - I think we do want to break out this sort of hierarch), but there's also switch room and TETRA rooms (TETRA is a two-way radio thing.)

Maybe we wait on adding equipment_room for a little bit until we have a better sense of how it's used.

**Comment by epaulson** [comment]
Team_Rooms are close to conference room, though I would picture them different. (Conference rooms are maybe booked for temporary stretches, team rooms are assigned more permanently - they're not quite offices or even open offices, nor are they classrooms or lab spaces, but they're kind of like that) we We'll talk a little bit more in Brick to see if we really need it or if we can find some kind of better "assignable space" designation type we can use, or if we just say "make a team room a room"

**Comment by epaulson** [comment]
Finally I should track down a few more references, but we've been trying to be better about aligning to other sources for some of our classifications - one we used for Brick was actually from the Federal US Dept of Education - a guide that gets used for reporting space usage in universities, the "Postsecondary Education Facilities Inventory and Classification Manual (FICM)": https://kb.wisc.edu/images/group198/94467/FICM2006Edition.pdf 

We weren't going to make classes for everything that's listed in FICM (or Omniclass/Uniclass/etc) so we just hit the highlights.

**Comment by sarahmacSE978** [comment]
I agree that we should differentiate a Team Room and a Conference Room based on Erik's definition above. I can ask how people are using Equipment room vs. Mechanical/Utility room.  Thanks!

**Comment by erikoskarwallin** [comment]
-- | -- | --
Brick type | Real Estate Core equivalent | Erik W's comment
Break_Room, Breakroom | StaffRoom | StaffRoom or RestingRoom could be used
Cubicle	None | None | Not sure this should be modelled as a Room, which we generally take to be an enclosed area (to some degree). Propose the use of [Workspace](https://dev.realestatecore.io/ontology/Space/Architecture/Zone/Workspace) (subclass of Zone) instead.
Equipment_Room | UtilitiesRoom | Has several subclasses for more precision
Janitor_Room | BackOffice | StorageRoom or StaffRoom or BackOffice
Lobby | Reception | What differentiates a Lobby from a Reception?
Lounge | None | Sure, should be added!
Mechanical_Room | UtilitiesRoom | Has several subclasses for more precision
Open_Office | OfficeLandscape | 
Team_Room | None | Is a Team room distinct from a ConferenceRoom

**Comment by epaulson** [comment]
I think Lobby and Reception are distinct and should be different classes, and a team room is distinct from a conference room and should also be a separate class. 

We can live with Equipment_Room and Mechanical_Room being UtilitesRoom for now, I think. 

We probably don't need to do anything special for Janitor_Room for now.
