### ISSUE TITLE
Relation mellan System och Loop saknas

### ISSUE THREAD

**Issue by KarlJonasHolmberg** [RealEstateCore/rec#244]
Hej

Vi sitter och håller på implementera REC men märker att jag inte kan sätta en relation mellan något "System" och någon "Loop", enligt Brics hemsida är det så de rekommenderar att sätta upp det, se bifogad bild 1.

En annan mindre bugg är att egenskaperna för "SetPoints" är dubblerade, jag antar att de ärver sina egna egenskaper, i REC4 miljön var detta ett ännu större problem där Sensor vad dubbel och SetPoint var trippel, men i senaste releasen verkar ni ha löst en ärvning i alla fall. Se bifogad bild 2.

![image](https://github.com/RealEstateCore/rec/assets/110527550/8009ab03-105d-4f77-9e56-81fc3e17ad3d)
![image](https://github.com/RealEstateCore/rec/assets/110527550/c09c839a-6194-430d-b12a-e928495f25ac)

/Jonas.Holmberg@Riksbyggen.se (+46) 0737-303490

**Comment by hammar** [comment]
Hi,

We're looking into how we might relax the REC collection semantics to allow System to have a broader set of child classes. This is part of an ongoing effort with Brick to align closer for their upcoming 1.4 release. Thanks for bringing this up, it helped activate the discussion!

Re. the ADT Explorer: unfortunately we do not develop that software, so do not have insight to offer on its behavior in this scenario.

**Comment by hammar** [comment]
Decision at last REC Technical Committee meeting: members on the Brick-REC collaboration delegation are authorized to jointly with Brick implement design changes as needed, including this. Next call on that collaboration scheduled for next week.

**Comment by PeteHart** [comment]
Fixed with PR #254
