### ISSUE TITLE
Humidity Sensor doesn't contain lastKnownValue field

### ISSUE THREAD

**Issue by heidimao** [RealEstateCore/rec#248]
When creating Humidity_Sensor using the following model: https://github.com/RealEstateCore/rec/blob/main/Source/DTDLv2/Brick/Point/Sensor/Humidity-/Humidity_Sensor.json
The lastKnownValue field is missing, is it possible to create a lastKnownValue field for Humidity_Sensor?

Thanks

**Comment by hammar** [comment]
Hi,

As Humidity can be absolute or relative, which entails entirely different kinds of measurement units, we cannot on this level define a lastKnownValue field. However, the child classes Absolute_Humidity_Sensor (https://dev.realestatecore.io/ontology/Point/Sensor/Humidity-/Absolute-) and Relative_Humidity_Sensor (https://dev.realestatecore.io/ontology/Point/Sensor/Humidity-/Relative-/Relative_Humidity_Sensor) do have those fields. Could they be used instead?

**Comment by hammar** [comment]
Closing this thread due to inactivity. Feel free to reopen if you'd like to continue discussion.
