### ISSUE TITLE
Implement waste module

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#25]

**Comment by erikoskarwallin** [comment]
Extend QuantityKinds with sync to  https://www.globalreporting.org/standards/gri-standards-download-center/

**Comment by hammar** [comment]
Technical commitee decision 2020-05-25: @erikoskarwallin will submit based on ProptechOS extensions before end of June.

**Comment by erikoskarwallin** [comment]
Needed QuantityKind:
WasteDiverted
WasteTotal
