### ISSUE TITLE
why isMemberOf instead of memberOf?

### ISSUE THREAD

**Issue by jbkoh** [RealEstateCore/rec#252]
Hi there,

I expected REC was inhering The Organization Ontology for representing organization (https://www.w3.org/TR/vocab-org/, http://www.w3.org/ns/org#), but I found that REC is using isMemberOf instead of [memberOf](https://www.w3.org/TR/vocab-org/#org:memberOf). Any reason to choose a custom one over a standard one?

In the worst case, we could introduce an alias, but I'd like to see better standard alignment and wonder your thoughts.

Thanks!

**Comment by PeteHart** [comment]
Agree, seems inconsistent. Likely just a remniscence from earlier REC naming convention (in the REC 3 series the isMemberOf was used in connection with collections).

Suggest to include proposed change in 4.1. Decision in upcoming tech steering committee meeting.

**Comment by PeteHart** [comment]
Closed with PR #254
