### ISSUE TITLE
Implement "Lösöre" / "Assets" module

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#30]
We need to be able to represent things that are typically located inside real estate, but are not _part_of_ that real estate. E.g., equipment, furniture, etc. Also need to find a good term for describing this concept. "Assets" has multiple connotations, some of which make it inappropriate in a real estate context.

**Comment by PeteHart** [comment]
Have looked a little into this domain.

In Sweden the legal term for things that are part of a lease is "byggnadstillbehör". This appears to include appliances (sv vitvaror) and for instance cupboards in kitchen or bath room. Whereas stuff like furniture or small appliances (water cooker) or consumer electronics (TV) is likely not part of the definition. The latter would fit better under the Swedish term "losöre". The term "lösöre" would for instance translate to movables.

In the BIM world it appears that the IFC Element has two sub classes IFC FurnishingElement and IFC EquipmentElement which implies that at least "byggnadstillbehör" can be modelled as either of these, or both.

A module to support this domain would consequently have to include at least the classes Element and Movable. Element can also be a more specific term such as FurnishingElement or EquipmentElement. Or these two can be sub-classes to Element. Movable can aslo be made more specific (sub classed) as Electronics, Small Appliances, Furniture, etc.

**Comment by hammar** [comment]
A need for this has also been expressed by other partners, e.g., the possibility of modeling (and ideally renting/leasing) a single Desk within a building. 

This might not necessarily be its own module, it might instead be used by other modules and therefore fit in the core.

Perhaps also relates to BOT alignment (#78), if we consider that these assets (for lack of a better word) need to be represented in some sort of spatial topology of the building (even thought they are not part of it)

**Comment by hammar** [comment]
Closed in Develop branch; Asset module is in place (feel free to develop and submit new asset subclasses)
