### ISSUE TITLE
Add streaming API definitions/guidance

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#32]
MQTT, Kafka, WebSockets, ...?

**Comment by sweco-secfbr** [comment]
WebSockets

**Comment by hammar** [comment]
Wow, this is an ancient issue. Will try and raise it from the dead at next REC Technical Committee, to see if we get it done by REC4 general availability later this fall.

**Comment by hammar** [comment]
Closed per decision at REC TC call November 7. Insufficient customer/user demand to prioritize at present.
