### ISSUE TITLE
Implement Annotations module

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#36]
A generic vocabulary for annotating REC objects with business data from other applications/systems, including some way of segmenting and grouping those annotations by system/namespace. 

Not to be confused with OWL annotation properties.

**Comment by hammar** [comment]
This might be the `customProperties` field (in DTDL a nested map, i.e., `map(string -> map(string->string))`) that has been discussed on a couple of ocassions but not yet implemented. I would like to revisit this discussion. Putting it on the REC TC agenda for next meeting, and am requesting TC members survey their customer/user needs.

**Comment by PeteHart** [comment]
While (fairly) easy to implement in DTDL I wonder if SHACL supports this kind of construct? Today we typically implement custom  properties with inheritance (ie inherit a model and add necessary properties) which is fairly easy in DTDL.

**Comment by hammar** [comment]
At REC Technical Committee 7 November, decision was as follows: we will set up a 1-hour working call on the need for annotations/tags among REC users. Partners who we know use such features include Idun and Willow, so these should be present if possible, plus as much of TC and other interested stakeholders as possible. Sufficient annotations support is a requirement for REC4 GA.

**Comment by hammar** [comment]
Implemented in PR #203, waiting to be merged.
