### ISSUE TITLE
hasType pattern on QuantityKind, PlacementContext, MeasurementUnit

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#44]
The "hasType" design pattern implemented in 3.1 for Rooms makes querying of underlying graph DB or triple store for the individuals much easier. Also it would be more homogenous to use the "hasType" pattern across the full ontology.

Recommended for 3.2. May be implemented similar to 3.1 where punning is used. The previous subclasses are deprecated but will remain at least until 4.0.

**Comment by hammar** [comment]
See discussion in #76 which relates to this (and feel free to contribute comments there or on the Gitter channel)

**Comment by hammar** [comment]
Closed as consequence of #76, but will reopen if needed after next tech committee meeting.
