### ISSUE TITLE
Named Individual core:RelativeHumidity wrongly typed

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#45]
In 3.1 the core:RelativeHumidity is of type core:MeasurementUnit, should be core:QuantityKind I believe

**Comment by hammar** [comment]
Hi,

I believe this is in fact correct; core:Humidity is the Quality Kind, core:RelativeHumidity is a measurement unit for said qualitykind (see the comment on the latter: "Relative Humidity. The amount of water vapour present in air expressed as a percentage of the amount needed for saturation at the same temperature."). It could perhaps be clarified by renaming to, e.g., "RelativeHumidityPercentage" or something similar, but I don't know the domain well enough to say for certain.

If you think I'm wrong on this or that it needs further discussion, feel free to re-open this issue. 

Cheers,

Karl

**Comment by PeteHart** [comment]
Good eye, I agree with your conclusion, there seem to be several types of Humidity, of which RH is one measured in % (I do not think we need to change the MU to RelativeHumidityPercentage, should go without saying), and others are Specific Humidity (g/kg) and Absolute Humidity (g/m3). Don't think we need to add those unless specifically requested. Key thing is that many room sensors measure RH and we need to be able to model that. We stick to our guns.
