### ISSUE TITLE
Missing support for outdoor stuff on real estate

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#48]
Things like outdoor parking lots, bicycle parking, sheds, play grounds etc may need classes of their own!?

Could be RealEstateComponents or separate root class.

**Comment by ektrah** [comment]
IMHO that would be useful to have. Maybe like this?

* rec:Space
    * rec:Architecture
        * rec:Building
        * rec:Level
        * ***rec:OutdoorSpace***
            * *rec:Balcony*
            * *rec:Courtyard*
            * *rec:Driveway*
            * *rec:Garden*
            * *rec:ParkingLot*
            * *rec:Playground*
            * *rec:Terrace*
                * *rec:RoofTerrace*
            * *...*
        * rec:Room
        * rec:Site
        * rec:SubBuilding
        * rec:Zone
    * rec:Region

**Comment by hammar** [comment]
Thanks for the suggested list! Agree that this would be useful. Let's try and get it into REC4. I'm CC:ing other REC TC members on this to raise visibility; hopefully we can take a decision at the next call on Monday. @PeteHart @joakimeriksson @erikoskarwallin @perkarlberg 

A challenge: The terms "Balcony" and "Terrace" are already in the ontology, but as a BuildingComponents (REC3) / BuildingElements (REC4) -- that is to say, the slab of material jutting out from the building (balcony) or underlying the terrace space, not the spatial representation of the "room" that these slabs of material help form. I'm not intricately familiar with balcony nomenclature and whether there is an established terminology in industry that we can reuse, that takes into account this differentiation. "BalconySpace" might be one way forward, but for tangible classes that are actually meant to be instantiated, type-based naming feels a little ugly. Thoughts anyone?

**Comment by PeteHart** [comment]
Think it's a good list.

It would be beneficial to have a ParkingSlot as well. In certain cases it's the presence of the parking lot that matters, in others the individual slots may need to be modelled (for instance as they may be leased or reserved with a contract attached to them, or a charging pole may be allocated to them, etc).

As to balconies and terraces I believe they are needed as elements (formerly components) to be able to express a construction point, for instance I have cases with balconies on facades to support maintenance use cases. Also for minimizing non breaking changes I think they should stay.

However in the IoT case I suppose we would like to be able to express, for instance, a presence sensor on a balcony or terrace similar to in a room. In which case the balcony or terrace is more like a space. Agree, however, that a BalconySpace seems a little "theoretical". Wonder if we can embrace the outside room created implicitely by a balcony or terrace as an OutdoorRoom of some kind?

**Comment by hammar** [comment]
This was discussed at REC Technical Committee today, and the consensus was to create the OutdoorSpace class, but to leave specific subclasses undefined for now. Several of those subclasses could be ambiguous, some could exist outdoors and indoors depending on context, and we don't want to limit such potential use cases down the line. Will likely revisit this later and perhaps add subclasses at that point.

At that same meeting, we decided to remove the existing ParkingSlotHot and ParkingSlotCold classes, to be replaced by a Zone subclass, "ParkingSpace", and to relax Zone to allow it to exist outside of a building. In this way, we hope that external parking spaces can easily be modelled.

Those changes are now in a PR on the REC4 repo, see https://github.com/RealEstateCore/REC4/pull/14. That REC4 repo will be folded into this repo before release.
