### ISSUE TITLE
Connecting REC models to BIM models or point clouds

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#57]
This need has been brought up by several consortium members as well as external partners. We need a standardized way of connecting the building knowledge graph to external models/representation, where needed, such as CAD/BIM models, point clouds, etc. This may require some thinking and modeling prototypes, as well as further requirements elicitation from the partners in question.

**Comment by sweco-secfbr** [comment]
I have some suggestions for this topic if its still open?

**Comment by hammar** [comment]
The issue is in a sort of in-between-state, in that there is a documented practice for interlinking with non-RDF-data that several consortium partners employ in their platforms (see https://github.com/RealEstateCore/rec/blob/master/docs/InstanceAlignment.md) but no official REC model support specific to CAD/BIM models.

**Comment by hammar** [comment]
Any suggestions are welcome!

**Comment by hammar** [comment]
For SHACL, that instance alignment suggestion is the preferred way forward. However that link to instance alignment guidance is now dead since REC4 release, I'll make sure to extract the content and publish as a guide on the dev site within a week or two.

For DTDL, we have the externalIds property (map string->string) intended to represent IDs in other systems, that also allows such outlinks. Going beyond this (providing semantics for connection protocols etc) is probably too ambitiuous for REC at this point.
