### ISSUE TITLE
Maximum occupancy on ConferenceRoom

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#74]
Typically conference rooms have a maximum occupancy, used for instance by booking systems. A data property for expressing this should be added to Room.

Note, may be relevant for other rooms than conference rooms, eg elevators, larger arenas due to fire regulations etc.

**Comment by PeteHart** [comment]
It may be possible to leverage the dataschemas:maximum in some way or another, to be explored.

**Comment by PeteHart** [comment]
For anything with chairs (meeting rooms over theaters to arenas) "seatingCapacity" would do. However, for supporting other "spaces" without chairs (eg an elevator) perhaps plain "capacity" would be better.

**Comment by erikoskarwallin** [comment]
Or CapacityPeople (to be consistent with "NumPeople")

**Comment by erikoskarwallin** [comment]
True! My mistake.

If we can construct a prop without "seating" then it would be easy to use (as you say) also in e.g. an elevator

So it should be something like"hasPeopleCapacity", not 100-perfect ...

**Comment by PeteHart** [comment]
@hammar sounds like a very good idea, think domain can be open so that potential theaters, arenas etc also can use it?

**Comment by erikoskarwallin** [comment]
Top!

**Comment by hammar** [comment]
Implemented in 538c513 (due to be merged into develop before 3.3 release)
