### ISSUE TITLE
Re-think property naming/structure

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#77]
REC property naming is a bit messy. Some properties use rather descriptive names that don't look quite "natural" in translations to JSON-LD or other formats (e.g., "hasSubBuildingComponent", "eventMeasurementUnit", etc). Other properties are more tersely named, which works for such translation to other formats, but which looks a little out-of-line compared with the more expressive name style (e.g., "dataSchema", "servedBy", etc).

For 3.2 we had originally planned to simplify and homogenize naming, see #20. However, taking into consideration currently deployed systems and maintainability challenges, we reverted and postponed those changes, see #67. At some point in the future, we'll need to handle this thing though, either in a feature release 3.3./3.4 (keeping but deprecating the older property names) or in a compatibility-breaking major release (4.0).

Tagging w/ 3.X in the meanwhile, so we don't lose track of this for the next Tech Committee meeting.

**Comment by PeteHart** [comment]
Think this is solved by REC 4... close?

**Comment by hammar** [comment]
Agree, closing.
