### ISSUE TITLE
New room types

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#83]
Suggested by a partner. Double-check existing room types for duplicates, then add the below:

- CableRoom
- Cafeteria
- ElevatorFreight
- LoadingReceiving
- MailRoom
- MeditationRoom
- MothersRoom
- MultiPurposeRoom
- SecurityRoom
- SprinklerRoom
- Storage

**Comment by erikoskarwallin** [comment]
Could be covered by already existing room:
CableRoom -> TelecommunicationRoom
MeditationRoom -> RestingRoom
MailRoom -> BackOffice
Cafeteria -> CoffeRoom (or change to Cafeteria)
ElevatorFreight -> ElevatorRoom (or?...)
LoadingReceiving -> EntranceService ?

Storage already exists

**Comment by hammar** [comment]
@erikoskarwallin I would say that some of the suggestions aren't functionally equivalent to what we have, and warrant inclusion. A meditation room is, to my mind, quite different from a resting room, a back office is more generic than a mail room, and a CableRoom and a TelecommunicationRoom are, I guess not equivalent (I assume there are cables that aren't for telecom purposes?).

But there are certainly ones that overlap with what we have:

* Storage -- we already have it as you point out.
* ElevatorFreight -- this is a piece of equipment, not a room. It is mounted in an ElevatorShaft, which is an existing room type. I understand the existing ElevatorRoom class that we have to be, e.g., the engineering/wiring/utilities space for a given elevator shaft and the elevator that it hosts?
* Cafeteria -- we already have CoffeeRoom. Possibly Cafeteria is a better and more established term though? Keeping in mind that a cafeteria is possibly a little broader, sometimes synonymous with "canteen" ("matsal"), etc. But I'm OK with changing to use Cafeteria.

**Comment by erikoskarwallin** [comment]
@hammar 
Good comments :-) Agree on Meditation
ElevatorFreight - should it be a Device/Equipment type then? (i.e. not a Room)?
Totally agree that Cafeteria is better than CoffeRoom (should we do a sameAs until 4.x?)
Should we add CableRoom as subclass to UtilityRoom? and possible put TelecommunicationRoom as sub to CableRoom?
Same for MailRoom - subclass to BackOffice?

**Comment by hammar** [comment]
Closed in development branch.
