### ISSUE TITLE
Rename Lantmäteriet module -> LFR

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#86]
As noticed by @PeteHart, the IRI https://w3id.org/rec/lantmäteriet/3.2/ blows up, probably due to non-ASCII characters breaking the .htaccess redirect. We should rename it to https://w3id.org/rec/lfr/3.2/ to avoid this.

**Comment by PeteHart** [comment]
Can we release a 3.2.1 immediately to rectify?

**Comment by erikoskarwallin** [comment]
ok

**Comment by hammar** [comment]
Should we do this in 3.2.1 (with new IRI:s, new release notes, etc) or simply backport onto the exiting 3.2 release? There's no change to the semantics of the model, only a single file name modification. I'm OK with not re-building the docs and everything that comes with it, just for this change.

**Comment by PeteHart** [comment]
I’m ok with staying at 3.2

**Comment by hammar** [comment]
OK, I'm working on it and hope to have this sorted today.
