### ISSUE TITLE
Implement an alias property

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#9]
Entities sourced from existing systems may have multiple "aliases", i.e. identifiers that are unique for and derive from each source system, but that are not necessarily unique in the joint REC-formatted dataset. We need to be able to represent and query for such aliases, but also to ensure that they do not collide. Suggestion:

1) (for implementing systems) Mint new IRI:s for the aliases based on the source system(s), e.g., "http://ns.vasakronan.se/SomeLegacySystem#ABCD-1234".
2) (in the ontology, i.e., this issue ticket) Create an appropriate object property ("hasAlias?") for linking entities to such minted aliases. That property should be inverse functional, to indicate that no two entities may share aliases.

**Comment by hammar** [comment]
I've given this some more thought, and it may be a better suggestion to use the existing owl:sameAs predicate for this; it is specifically intended to merge identifiers across systems. If needed, we could then in code reserve certain namespaces (either URIs or URNs) to indicate that they are explicitly intended for mapping of identifiers against legacy systems, and that it is the responsibility of the implementor to do something reasonable with such namespaces. Comments on this idea are appreciated.

**Comment by erikoskarwallin** [comment]
I concur: sameAs is better then aliasId

**Comment by hammar** [comment]
Was discussed at workshop at Vasakronan August 29. Unfortunately this thread was forgotten and we reverted back to discussing a property ":hasAliasID" and how to document it. Let's revisit this on Slack and get to a decision ASAP. This is on me to drive and close.

**Comment by hammar** [comment]
:hasAliasId is deprecated and I will write a documentation/recommendation on how to use rdfs:seeAlso / owl:sameAs for such entity alignment, which will be included prominently in the Git repo. Will close once that is in place.
