### ISSUE TITLE
Updates to modelling for presence use cases

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#90]
Currently (3.2) the support for presence and motion is rudimentary. In particular relevant PlacementContexts (PC) are needed. It is suggested to update as follows

For presence (sv närvaro) two cases have been identified; 1) presence in rooms and 2) presence at desks (or exercise equipment, or similar)

It is suggested to introduce a **new PC "Place"** that may be used to indicate that the media or context of the sensor is a place (sv plats/utrymme/ställe) which can be abstracted to both of the above use cases 1) and 2)

For use case 1), presence in room, it may either be a A) simple sensor indicating that some people are present or B) a sensor capable of counting the number of people.

Either ways the types of values that may be detected may be abstracted to a **new QuantityKind (QK) "Occupancy"**. To distinguish between the simple (A) and counting (B) use cases the MeasurementUnit (MU) can use the existing BooleanDetection and NumPeople respectively. 

The existing QK "AreaPresence" (used for counting use cases) can be deprecated.

The existing QK "Presence" should be kept as it may be used where presence of a phenomenon is needed (not if a resource is occupied)

An additional advantage of the proposed QK **"Occupancy"** is that it plays well with output from conference room reservation systems. Ie use cases where reservations will be correlated with real world usage.

For motion (flow) use cases with people moving in hallways, through doors etc there's support with the PCs "DirectionIn/Out" and QK "Footfall" (an industry term) and MU "NumPeople" is already implemented.

**Comment by jgentzell** [comment]
How is the thinking around manage number of people in a room based on footfall data, example you have basic sensor that detects entrance and exits of an room, its send periodical data every 5 minutes, so basically you get a counter of every entrance (A) and every exits (B), together the get you a delta (A-B) of the change of number of people during the 5 minutes. Is this delta you see is the QK Footfall with MU NumPeople?

**Comment by PeteHart** [comment]
@jgentzell please note the issue is a proposal and other solution proposals are welcome. I’m not an expert on this domain but had understood that the term “footfall” refers to the number of people entering, and hence, not the delta. So your case, with this interpretation, would require another QK to represent the delta or change in people, which may have an industry term as well, I’m just not aware?

**Comment by jgentzell** [comment]
@PeteHart same here really, in todays discussion we said that we implement as you state in the proposal, two sensors with QK Footfall, on for PC DirectionIn and one for PC DirectionOut, and leave the delta/count to application side. If I found out any industry term I will comment later.

**Comment by erikoskarwallin** [comment]
We also need a definition of max occupancy/seating/... e.g. maxCapacity or maxSeating

**Comment by PeteHart** [comment]
I think this was fixed by @hammer in closing of #74 expressing a property _hasPeopleCapacity_ or something like that, in line with ongoing Willow modeling (in relation to capacity of elevator)

**Comment by hammar** [comment]
I believe this is closed by merging of #94 but if I'm mistaken, feel free to re-open.

**Comment by hammar** [comment]
I'm obviously mistaken. Mea culpa! :-)

**Comment by PeteHart** [comment]
@hammar for this one we’re wait for @perkarlberg  to update with his insights re TC meeting

**Comment by hammar** [comment]
Where are we on this? I believe that all other blockers for 3.3 release have been handled.

**Comment by PeteHart** [comment]
I believe the occupancy aspects of this is covered in BRICK. For boolean occupancy an Occupancy Status exists. Which also seem to be the purpose of the Occupancy Sensor. For counting amount of people present Occupancy count may be used.

For the people moving (flow) aspect Motion Sensor exist. However, unclear if this covers the footfall cases.

The issue may be closed in REC and clarified with, and potentially moved to, BRICK.

**Comment by hammar** [comment]
Agreed, closing.
