### ISSUE TITLE
Add property register data propert

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#91]
Through work with Castellum its become clear that it'd be beneficial with a reference to the property register designation (sv fastighetsbeteckning) in the country where the real estate is located.

This has now been implemented in Castellum's own add-on ontology to REC as a data property `hasPropertyRegisterDesignation` that in turn is a sub property to `hasAuxiliaryData`.

It is suggested to bring this artefact into REC in 3.3.

Note, there's also a need to change in the LFR module, however since this is much more detailed and only covers the Swedish property register a more general solution like proposed above also makes sense.

**Comment by PeteHart** [comment]
I did a swift analysis of the existence of property registers across the EU. A list of registers here https://e-justice.europa.eu/content_land_registers_in_member_states-109-be-en.do?member=1

All but 2 or 3 has a register. All the registers but a couple are digital. Hence it appears reasonable to introduce a data property for keeping the identity in such register.

With new naming conventions for data properties the name proposed is `propertyRegisterDesignation`

**Comment by hammar** [comment]
Sounds good to me! I'll be merging feature-willowmodels into dev shortly (I believe we have consensus on those designs), so if you want to implement this property on the dev branch (either directly or through a short-lived feature branch), feel free to do so.

**Comment by PeteHart** [comment]
OK, I’ll create a PR on the dev branch tomorrow
