### ISSUE TITLE
Support for work stations / desks needed

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#92]
A typical use case for open office environments is detection of presence or occupancy of individual work stations / work desks. Would be beneficial with REC support for this kind of artefact.

Note, not really a furniture thing (which is needed too) but rather that a number of furnitures together (eg desk, chair, ...) are administratively seen as a resource that may or may not be occupied.

Perhaps we need a resources module that can abstract various artefacts with similar "seizable" behaviour (could also be a training equipment in a gym).

**Comment by joakimeriksson** [comment]
I do think we should bring in someone from Altacogni here - as they are very competent in that specific area (e.g. the company that now own the Yanzi Networks assets and are the same tech team).

**Comment by erikoskarwallin** [comment]
I suggest we Meet very soon. Friday 18/9 CET10.00?; Monday 21/9 CET13.00-; Tuesday 22/9 CET15.00- ?
We need to model e.g. "OfficeDesk" as well we need PlacementContext:UnderOfficeDesk etc.
We could start with office basics.

**Comment by PeteHart** [comment]
Båda måndag och tisdag funkar för mig, föredrar dock måndag? Mvh Peter

Sendt fra min iPad

**Comment by jgentzell** [comment]
Have you considered meta data for desk occupancy, example: how long time after the sensor detects non-activity its should wait until it sends unoccupied? (reason why mfg implemented this function is to minimized fault detections, this is not the same as business configuration in the application layer) /best regards Johan G

**Comment by PeteHart** [comment]
@jgentzell no I hadn’t really thought about that aspect, so far REC hasn’t focused on such meta data for the sensory systems, this has been implementation specific. I spontaneously think the data schema could be used for modelling a configuration but would require object properties for sensor configurations, something similar to the analysis configuration in the analytics module, will contemplate more...

**Comment by PeteHart** [comment]
With the proposed new components in REC (re the feature-willowmodels branch) several solutions appear to be possible without further additions.

1) The workstation is ether modelled as an Asset:Furniture:Desk or a Collection:AssetCollection:FurnitureCollection of relevant furnitures (desk, chair, ...) and then the Asset or the Collection is associated with (hasCapability) Capability:Sensor:OccupancySensor

2) The spatial extent of the desk is modelled as Space:Zone (a specific subclass may be defined for this, name TBD) and the same construct with hasCapability as in 1) above is used - this setup would be similar for a cubicle

**Comment by hammar** [comment]
Hi,

At discussions with MS, Willow, and Vergesense (who make occupancy measurement sensors) earlier today, the second approach (subclass of Zone with a reasonable name) was much preferred. Such sensors are typically ceiling-mounted and a zone is "drawn in" on their detection area using some admin software tooling. These zones (or as they call them, "partitions")  are not tied immediately to the furniture in the zone, but rather represent a spatial zone of some size (that can in turn include arbitrary furniture and people counts).

If you are OK with both listed options, I propose to continue with the second, in conjunction with the MS/Willow/Vergesense team, and will update the REC models (either in feature-willowmodels or in develop branch) accordingly within a few days. OK?

**Comment by PeteHart** [comment]
Yes @hammar, I concur with proposed approach

**Comment by hammar** [comment]
Closed in develop branch (through Zone/Workspace)
